name: Check
on:
  push:
    branches:
    - main
    - workflow_check
  pull_request:
    branches:
    - main

jobs:
  check:
    name: Check
    runs-on: windows-2022
    timeout-minutes: 5
    env:
      # Emit backtraces on panics.
      RUST_BACKTRACE: full
    steps:
      - name: Print windmc path
        shell: pwsh
        run: which.exe windmc.exe

      # The next step needs `rust-toolchain.toml`
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Sync toolchain
        shell: bash
        run: rustup show

      - name: Copy dummy messages for test
        shell: pwsh
        run: Copy-Item ".\.github\Mech3Msg.json" -Destination "."

      - name: Run cargo check
        shell: bash
        run: cargo check --release

      - name: Run cargo fmt
        shell: bash
        run: cargo fmt -- --check

      - name: Run cargo build
        shell: bash
        run: cargo build --release --verbose

      - name: Persist produced DLL for manual checking
        uses: actions/upload-artifact@v2
        with:
          name: release-build
          path: target/i686-pc-windows-gnu/release/mech3msg.dll

      - name: Setup 32-bit Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x86'

      - name: Run Python functional tests
        run: python tests.py "./target/i686-pc-windows-gnu/release/mech3msg.dll"
