name: Check
on:
  push:
    branches:
    - master
    - workflow_check
  pull_request:
    branches:
    - master
  schedule:
  # At 11:00 (UTC) on day-of-month 25
  - cron: '0 11 25 * *'
jobs:
  check:
    name: Check
    runs-on: windows-latest
    timeout-minutes: 5
    env:
      # Emit backtraces on panics.
      RUST_BACKTRACE: full
    steps:
      - name: Print windmc path
        shell: pwsh
        run: which.exe windmc.exe

      - uses: actions/checkout@v2
      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: i686-pc-windows-msvc
          components: rustfmt

      - name: Copy dummy messages for test
        shell: pwsh
        run: Copy-Item ".\.github\Mech3Msg.json" -Destination "."

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --release --target "i686-pc-windows-msvc"

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target "i686-pc-windows-msvc" --verbose

      - name: Persist produced DLL for manual checking
        uses: actions/upload-artifact@v2
        with:
          name: release-build
          path: target/i686-pc-windows-msvc/release/mech3msg.dll

      - name: Setup 32-bit Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x86'

      - name: Run Python functional tests
        run: python tests.py "./target/i686-pc-windows-msvc/release/mech3msg.dll"
